# Generated by Django 5.0.2 on 2024-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_alter_recipe_description_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(through='recipes_app.RecipeCategory', to='recipes_app.category'),
        ),
    ]
